language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: bKSSf2COpL2dN7tBRenKg4bNlMHFbogjKU2rl+g5veVsQfbpcQ1szyZmcSn0uFDXrldTH40wtXcmYO+UQrd188pWS6AyLZ4SyUeeiSFvuzt2z6dVohSyl8vZ9hi6K+xfTOaj5h772P98FZAilmlIia3XZQ9SPj4FjMqH+CxeKT4=
  - secure: BKLE7jwflH9OOEUqmY6X65sPb6WdYQGV02ITZVR0zz9T6MRMUjX9hKv/x/TfsvaiaTK13uI2CawaTCmBVar5r0VAlKOoe7avJFkAoSAkuywq89cRg6JBV0eUkCIrHFYA9bEfKUhq1he2CXMDg3AhOoP+yCVDnuGAGKQoMf4HT1U=
