language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: djwfa3voudglZZlAcNaaHs7GWILz56hQtSSU93Dc9XW2+zwWtNrl3XInawo1c7/xOdxiP7ssVeTST3BHR3ahjuv7DsXMFQ7XMbCJ0+a0BTyvrHclXj/jJA0lXRaChUiLZG3sxSFy/cor0JPmtHS7PwhJZvE9kXtKkWVbGlDjWEg=
  - secure: USv3YSCw7wyhlIBg0aN8CufJVRlHxsaJozrTqVCtQI7A6d1Ds9SM30wHBY2dKvHU72WmaoYMXSu1HG4dPq76rYgXUm3l5/GO/TbXSdf3F1YdKvESdL6t7CGhtYSS3A56DM0XPFJpHfV7V5H3urlYAZa7FXzP4CT5z81aDSTjOYk=
  - secure: U+WRvPn12wv9xb84IMKjSOP3XvVYFYngCBNQbHVu4HsLadizEfdsw1/NWJxadxAFvAQoJxPt+O4BcaDQJkCBx4Y6IhIJ2KgXjE4XA5TkY0OhvZaFvUdRkblY1w3nBtAb4wCJ0AKmJtJyttTgh3XvWcQIMtrH+cHfeKcrmCB5kmQ=
